### ISSUE TITLE
Need improve 

### ISSUE THREAD

**Issue by Nightenom** [pschichtel/ts3server-package#2]
Hello, nicely done, great job, but:
1. cp command (cp -R base/\* "$build") at start of build.sh doesnt work -> i need to put whole path to download directory
2. dpkg-deb buils told me that: fail: control folder has bad permissions 700 (must be >=0755 and <=0775)

**Comment by pschichtel** [comment]
Ha... I never noticed this issue. I guess better answering late than never :)

> cp command (cp -R base/* "$build") at start of build.sh doesnt work -> i need to put whole path to download directory

do you mean I should convert the relative ```base/*``` to an absolute path to make it working directory independent?

> dpkg-deb buils told me that: fail: control folder has bad permissions 700 (must be >=0755 and <=0775)

Didn't ever encounter this, but after looking at the code... I don't explicitly assign permissions anywhere except for the ts3server binary, but I really should.

**Comment by Nightenom** [comment]
Hello, it's year and half and I'm not able to check it till 28th August so I can't answer you now :D

And I remember that I was searching for ts3_server for armhf architecture, but I can test it on i386

**Comment by Nightenom** [comment]
Hello again,
as I'm unable to recover the things I have been doing with this (on pc and even in my head :D), we can close this issue.

Sincerely Nightenom

**Comment by pschichtel** [comment]
Yeah, I'll probably switch to a Docker container anyway.
